# Generated by Django 2.2 on 2022-06-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220617_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='category',
            new_name='category_field',
        ),
    ]
